### ISSUE TITLE
Error building speculos - Preparing metadata (pyproject.toml): finished with status 'error' - M1 max - ARM64

### ISSUE THREAD

**Issue by valber-ledger** [LedgerHQ/speculos#462]
## Description
I tried to build speculos, but I had an issue on ARM architecture at the following step: 
`ERROR [nanos stage-1 6/8] RUN pipenv install --deploy --system`

The issue came from the file pyproject.toml:
`Preparing metadata (pyproject.toml): finished with status 'error'`

There is some logs:
```
3.831 [pipenv.exceptions.InstallError]:   Installing build dependencies: started
3.831 [pipenv.exceptions.InstallError]:   Installing build dependencies: finished with status 'done'
3.831 [pipenv.exceptions.InstallError]:   Getting requirements to build wheel: started
3.831 [pipenv.exceptions.InstallError]:   Getting requirements to build wheel: finished with status 'done'
3.831 [pipenv.exceptions.InstallError]:   Preparing metadata (pyproject.toml): started
3.831 [pipenv.exceptions.InstallError]:   Preparing metadata (pyproject.toml): finished with status 'error'
3.831 [pipenv.exceptions.InstallError]: error: subprocess-exited-with-error
3.831 [pipenv.exceptions.InstallError]:
3.831 [pipenv.exceptions.InstallError]:   × Preparing metadata (pyproject.toml) did not run successfully.
3.831 [pipenv.exceptions.InstallError]:   │ exit code: 1
3.831 [pipenv.exceptions.InstallError]:   ╰─> [23 lines of output]
3.831 [pipenv.exceptions.InstallError]:       pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
3.831 [pipenv.exceptions.InstallError]:       Traceback (most recent call last):
3.831 [pipenv.exceptions.InstallError]:         File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
3.831 [pipenv.exceptions.InstallError]:           main()
3.831 [pipenv.exceptions.InstallError]:         File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
3.831 [pipenv.exceptions.InstallError]:           json_out['return_val'] = hook(**hook_input['kwargs'])
3.831 [pipenv.exceptions.InstallError]:         File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
3.831 [pipenv.exceptions.InstallError]:           whl_basename = backend.build_wheel(metadata_directory, config_settings)
3.831 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-x6lquuzp/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 46, in build_wheel
3.831 [pipenv.exceptions.InstallError]:           project = AbstractProject.bootstrap('wheel',
3.831 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-x6lquuzp/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 92, in bootstrap
3.831 [pipenv.exceptions.InstallError]:           project.setup(pyproject, tool, tool_description)
3.831 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-x6lquuzp/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 587, in setup
3.831 [pipenv.exceptions.InstallError]:           self.apply_user_defaults(tool)
3.831 [pipenv.exceptions.InstallError]:         File "project.py", line 68, in apply_user_defaults
3.831 [pipenv.exceptions.InstallError]:           super().apply_user_defaults(tool)
3.831 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-x6lquuzp/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
3.831 [pipenv.exceptions.InstallError]:           super().apply_user_defaults(tool)
3.831 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-x6lquuzp/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
3.831 [pipenv.exceptions.InstallError]:           self.builder.apply_user_defaults(tool)
3.831 [pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-x6lquuzp/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
3.831 [pipenv.exceptions.InstallError]:           raise PyProjectOptionException('qmake',
3.831 [pipenv.exceptions.InstallError]:       sipbuild.pyproject.PyProjectOptionException
3.831 [pipenv.exceptions.InstallError]:       [end of output]
3.831 [pipenv.exceptions.InstallError]:
3.831 [pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.
3.831 [pipenv.exceptions.InstallError]: error: metadata-generation-failed
3.831 [pipenv.exceptions.InstallError]:
3.831 [pipenv.exceptions.InstallError]: × Encountered error while generating package metadata.
3.831 [pipenv.exceptions.InstallError]: ╰─> See above for output.
3.831 [pipenv.exceptions.InstallError]:
3.831 [pipenv.exceptions.InstallError]: note: This is an issue with the package mentioned above, not pip.
3.831 [pipenv.exceptions.InstallError]: hint: See above for details.
3.831 ERROR: Couldn't install package: {}
3.831  Package installation failed...
3.837 /usr/local/lib/python3.9/subprocess.py:1052: ResourceWarning: subprocess 11 is still running
3.837   _warn("subprocess %s is still running" % self.pid,
3.837 ResourceWarning: Enable tracemalloc to get the object allocation traceback
3.837 sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=4 encoding='utf-8'>
3.837 ResourceWarning: Enable tracemalloc to get the object allocation traceback
3.837 sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=7 encoding='utf-8'>
3.837 ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
The issue has come from the following commit (implémentation of pyqt5) :  LedgerHQ/speculos@97a1eb9 

### Workaround
Commit [[ci][update] Codecov wasn't working for months, updated from v1 to v4]  LedgerHQ/speculos@df84117

`git checkout df84117d2ac300cd277d58913a9f56e061b5fb2f`
`docker build -t speculos-builder:latest -f build.Dockerfile .`

Modify Dockerfile: `FROM speculos-builder:latest AS builder` 

Build and run speculos: `docker-compose build && docker-compose up`

**Comment by lpascal-ledger** [comment]
`pyqt5` hs been removed from the Speculos Docker image, this bug should be resolved.
